
SELECT * FROM STUDENT;

SELECT * FROM COURSE;

SELECT * FROM ENROLLMENT;


SELECT N.STUDENT_ID,
N.NAME AS STUDENT_NAME,
K.COURSE_NAME,
K.FACULTY,
M.MARKS
FROM STUDENT N
INNER JOIN ENROLLMENT M 
ON N.STUDENT_ID = M.STUDENT_ID
INNER JOIN COURSE K
ON M.COURSE_ID = K.COURSE_ID;


SELECT K.COURSE_NAME,
COUNT(M.STUDENT_ID) AS TOTAL_STUDENTS
FROM COURSE K
INNER JOIN ENROLLMENT M
ON K.COURSE_ID = M.COURSE_ID
GROUP BY K.COURSE_NAME
HAVING COUNT(M.STUDENT_ID) >= 1;
