
CREATE DATABASE STUDENT_DATA_BASE;

USE STUDENT_DATA_BASE;

CREATE TABLE STUDENT(
  STUDENT_ID INT PRIMARY KEY,
  NAME VARCHAR(50),
  AGE INT NOT NULL,
  CITY VARCHAR(50)
);

CREATE TABLE COURSE (
  COURSE_ID INT PRIMARY KEY,
  COURSE_NAME VARCHAR(50),
  FACULTY VARCHAR(50)
);

CREATE TABLE ENROLLMENT(
  ENROLL_ID INT PRIMARY KEY,
  STUDENT_ID INT NOT NULL,
  COURSE_ID INT,
  MARKS INT,
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);
